apiVersion: v1
kind: Service
metadata:
  name: dataux
  labels:
    app: dataux
spec:
  type: NodePort
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30036
  selector:
    app: dataux
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dataux
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dataux
    spec:
      containers:
      - name: dataux
        image: "gcr.io/dataux-io/dataux:v2017.03.15a"
        # un-comment this for testing, it will force pull latest image
        imagePullPolicy: Always
        command: ["/dataux", "--loglevel=debug"]
        ports:
        - containerPort: 4000